# Generated by Django 4.1.4 on 2022-12-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('discription', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Products/')),
            ],
        ),
    ]
